Rename Task List
elementary/tasks pull request #153
Opened 2020-10-10 10:56 UTC by marbetschar

For whatever reason, the new name does not get stored in the Nextcloud backend. This PR tries to fix this (WIP).

2020-10-10 13:52 UTC, alainm23 commented on src/ListView.vala
> +                source.write.begin (null, (obj,res) => {
Add a space after `obj,`
`source.write.begin (null, (obj, res) => {`

2020-11-03 17:55 UTC, danrabbit requested changes

2020-11-03 17:55 UTC, danrabbit commented on src/ListView.vala
> +                        debug (@"WebDAV Rename '$(source.get_uid())'");
Can we use printf syntax here please:
```suggestion
                        debug ("WebDAV Rename: %s", source.get_uid ());
```

2020-11-03 17:55 UTC, danrabbit commented on src/ListView.vala
> +                        collection_source_webdav_session.credentials = credentials;
We can probably organize this is a bit more to keep like things together
```suggestion
                        var source_webdav_extension = (E.SourceWebdav) source.get_extension (E.SOURCE_EXTENSION_WEBDAV_BACKEND);

                        E.NamedParameters credentials;
                        var credentials_provider = new E.SourceCredentialsProvider (registry);
                        credentials_provider.lookup_sync (collection_source, null, out credentials);

                        var collection_source_webdav_session = new E.WebDAVSession (collection_source);
                        collection_source_webdav_session.credentials = credentials;
```

2020-11-03 17:55 UTC, danrabbit commented on src/ListView.vala
> +                        debug (@"Local Rename '$(source.get_uid())'");
```suggestion
                        debug ("Local Rename: %s", source.get_uid ());
```

2020-11-03 20:00 UTC, danrabbit requested changes

2020-11-03 20:00 UTC, danrabbit commented on src/ListView.vala
> +                    critical (e.message);
If we completely failed to rename the list, I think we should probably throw an error to the user

2020-11-03 20:00 UTC, danrabbit commented on src/ListView.vala
> +                        debug ("Local Rename: %s", source.get_uid ());
I also wonder if we should throw an error here. This means that we can't rename the list on the server right? So if a user renames a list and then goes to another device, they will be looking for a renamed list that doesn't exist. I would imagine we should inform them of that

2020-11-13 13:44 UTC, marbetschar commented
@danrabbit can you please re-review? I've done the following changes, including your suggestions:

- Moved the complexity of renaming a task list for different kind of backends into the `TaskModel`
- Throwing an error if we are not able to rename
- Display the error in a `Granite.MessageDialog`

I also had to change the `EditableLabel` a little bit,to avoid get the `changed` signal fired twice if the user hits the Enter key to submit the new task list name (aka "end editing in EditableLabel).

2020-11-17 16:16 UTC, marbetschar commented
@danrabbit friendly reminder :)
would be great if you review/merge these changes. If we're good here, I'll adapt PR #150  accordingly.

2020-11-17 19:54 UTC, danrabbit requested changes
Couple of small code style comments

I can't really test this because it doesn't work for my CalDav or GTasks lists, but at least the error messaging is working :)

2020-11-17 19:54 UTC, danrabbit commented on src/TaskModel.vala
> +            debug (@"WebDAV Rename '$(task_list.get_uid())'");
printf style please :) 
```suggestion
            debug ("WebDAV Rename", task_list.get_uid());
```

2020-11-17 19:54 UTC, danrabbit commented on src/TaskModel.vala
> +            debug (@"Local Rename '$(task_list.get_uid())'");
printf style here too

2020-11-17 20:41 UTC, marbetschar commented
@danrabbit fixed the requested code bits.

Yes, for some reason the WebDAV specific solution does not seem to work for the Google backend. Need to figure out how to do it there and [created an issue](https://github.com/elementary/tasks/issues/163) to keep track of it.

At least for regular WebDAV this solution works - so we should be fine for backends such as Nextcloud.

2020-11-18 02:22 UTC, danrabbit approved these changes

2020-11-18 03:53 UTC, merged