WebDAV: Delete Task List
elementary/tasks pull request #188
Opened 2021-02-04 14:34 UTC by marbetschar

This PR adds the functionality to delete Tasks Lists if they are either stored locally or in a WebDAV backend.

2021-03-12 20:09 UTC, danrabbit requested changes
I can confirm this works for local backend, just one comment

2021-03-12 20:09 UTC, danrabbit commented on src/TaskModel.vala
> +        var task_list_extension = (E.SourceTaskList) task_list.get_extension (E.SOURCE_EXTENSION_TASK_LIST);
Getting a compiler warning about this:
```
../src/TaskModel.vala:206.13-206.31: warning: local variable `task_list_extension' declared but never used
```

2021-03-16 08:21 UTC, marbetschar commented on src/TaskModel.vala
> +        var task_list_extension = (E.SourceTaskList) task_list.get_extension (E.SOURCE_EXTENSION_TASK_LIST);
Good catch! Removed the var.

2021-03-16 22:33 UTC, danrabbit approved these changes

2021-03-17 00:01 UTC, merged