Use Widget Namespace Widgets directory
elementary/tasks pull request #219
Opened 2021-04-12 15:02 UTC by marbetschar

This PR introduces a Widgets namespace for everything stored in the Widgets directory. This PR is relate dto https://github.com/elementary/tasks/issues/201 and https://github.com/elementary/tasks/pull/218.

2021-04-12 16:27 UTC, danrabbit requested changes
Don't forget to update POTFILES :)

2021-04-12 20:06 UTC, marbetschar commented
thanks! Each and every time I forget those :) Is the way I did it correct? ... and is there any easier way?

2021-04-13 18:54 UTC, danrabbit commented
@marbetschar `*.po` files will be updated automatically by Actions. You don't ever need to touch those. Only the `POTFILES` file needs to be updated

2021-04-13 18:55 UTC, danrabbit approved these changes

2021-04-13 18:55 UTC, merged